### ISSUE TITLE
Quelle deadline pour le rendu du code et du rapport (.md)?

### ISSUE THREAD

**Issue by YoannLth** [PolytechLyon/4a-isi3-tp4-2016-2017-groupe-1-lathuiliere_montes#11]
Tout est dans le titre 😅
Jusqu'à quand peut on commit du code et du rapport? 🤔
@Slashgear

**Comment by Slashgear** [comment]
Histoire d'être clair et pour qu'il n'y ait pas d'ambiguïté.

La deadline pour le rendu du code et du rapport dans le Markdown c'est : 
**Vendredi 2 Juin à 18h**

Vous pouvez comme les autres fois me notifié que vous avez terminé avant cette date en ouvrant un issue pour me l'indiquer.

Message à relayer sur votre groupe

**Comment by YoannLth** [comment]
Ok merci, le message a été relayé sur le groupe 👍
